// frontend/angular-app/src/app/components/employee-list/employee-list.component.ts
import { Component, OnInit, inject, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { MatTableModule } from '@angular/material/table';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatCardModule } from '@angular/material/card';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatDialogModule, MatDialog } from '@angular/material/dialog';
import { MatInputModule } from '@angular/material/input';
import { MatFormFieldModule } from '@angular/material/form-field';
import { FormsModule } from '@angular/forms';

import { EmployeeService } from '../../services/employee.service';
import { Employee } from '../../models/employee.model';

@Component({
  selector: 'app-employee-list',
  standalone: true,
  imports: [
    CommonModule,
    MatTableModule,
    MatButtonModule,
    MatIconModule,
    MatCardModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
    MatDialogModule,
    MatInputModule,
    MatFormFieldModule,
    FormsModule
  ],
  template: `
    <div class="employee-list-container">
      <mat-card>
        <mat-card-header>
          <mat-card-title>
            <div class="header-actions">
              <h2>Gestión de Empleados</h2>
              <div class="actions">
                <div class="filters-container">
                  <mat-form-field appearance="outline" class="search-field">
                    <mat-label>Buscar empleados...</mat-label>
                    <input matInput 
                           [(ngModel)]="searchTerm" 
                           (input)="onSearchChange()"
                           placeholder="Buscar por nombre o cargo">
                    <mat-icon matSuffix>search</mat-icon>
                  </mat-form-field>
                  
                  <mat-form-field appearance="outline" class="salary-field">
                    <mat-label>Salario mínimo</mat-label>
                    <input matInput 
                           type="number" 
                           [(ngModel)]="minSalary" 
                           (input)="onSalaryFilterChange()" 
                           placeholder="0"
                           min="0">
                    <span matPrefix>$&nbsp;</span>
                  </mat-form-field>
                  
                  <mat-form-field appearance="outline" class="salary-field">
                    <mat-label>Salario máximo</mat-label>
                    <input matInput 
                           type="number" 
                           [(ngModel)]="maxSalary" 
                           (input)="onSalaryFilterChange()" 
                           placeholder="Sin límite"
                           min="0">
                    <span matPrefix>$&nbsp;</span>
                  </mat-form-field>
                  
                  <button 
                    mat-icon-button 
                    (click)="clearFilters()"
                    matTooltip="Limpiar filtros"
                    class="clear-filters-btn">
                    <mat-icon>clear</mat-icon>
                  </button>
                </div>
                
                <button 
                  mat-raised-button 
                  color="primary" 
                  (click)="createEmployee()">
                  <mat-icon>person_add</mat-icon>
                  Agregar Empleado
                </button>
              </div>
            </div>
          </mat-card-title>
        </mat-card-header>
        
        <mat-card-content>
          <div class="loading-container" *ngIf="employeeService.loading()">
            <mat-spinner></mat-spinner>
            <p>Cargando empleados...</p>
          </div>

          <div class="error-container" *ngIf="employeeService.error()">
            <mat-icon color="warn">error</mat-icon>
            <p>{{ employeeService.error() }}</p>
            <button mat-raised-button color="primary" (click)="refreshEmployees()">
              Intentar de nuevo
            </button>
          </div>

          <div class="table-container" *ngIf="!employeeService.loading() && !employeeService.error()">
            <table mat-table [dataSource]="filteredEmployees()" class="employees-table">
              <ng-container matColumnDef="fullName">
                <th mat-header-cell *matHeaderCellDef>Nombre Completo</th>
                <td mat-cell *matCellDef="let employee">
                  <strong>{{ employee.fullName }}</strong>
                </td>
              </ng-container>

              <ng-container matColumnDef="email">
                <th mat-header-cell *matHeaderCellDef>Correo Electrónico</th>
                <td mat-cell *matCellDef="let employee">
                  <a href="mailto:{{ employee.email }}">{{ employee.email }}</a>
                </td>
              </ng-container>

              <ng-container matColumnDef="position">
                <th mat-header-cell *matHeaderCellDef>Cargo</th>
                <td mat-cell *matCellDef="let employee">
                  {{ employee.position }}
                </td>
              </ng-container>

              <ng-container matColumnDef="salary">
                <th mat-header-cell *matHeaderCellDef>Salario</th>
                <td mat-cell *matCellDef="let employee">
                  {{ employee.salary | currency:'USD':'symbol':'1.0-0' }}
                </td>
              </ng-container>

              <ng-container matColumnDef="hireDate">
                <th mat-header-cell *matHeaderCellDef>Fecha de Contratación</th>
                <td mat-cell *matCellDef="let employee">
                  {{ employee.hireDate | date:'shortDate' }}
                </td>
              </ng-container>

              <ng-container matColumnDef="actions">
                <th mat-header-cell *matHeaderCellDef>Acciones</th>
                <td mat-cell *matCellDef="let employee">
                  <div class="action-buttons">
                    <button 
                      mat-icon-button 
                      color="primary"
                      (click)="viewEmployee(employee.id)"
                      matTooltip="Ver Detalles">
                      <mat-icon>visibility</mat-icon>
                    </button>
                    <button 
                      mat-icon-button 
                      color="accent"
                      (click)="editEmployee(employee.id)"
                      matTooltip="Editar Empleado">
                      <mat-icon>edit</mat-icon>
                    </button>
                    <button 
                      mat-icon-button 
                      color="warn"
                      (click)="confirmDelete(employee)"
                      matTooltip="Eliminar Empleado">
                      <mat-icon>delete</mat-icon>
                    </button>
                  </div>
                </td>
              </ng-container>

              <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
              <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
            </table>

            <div class="no-data" *ngIf="filteredEmployees().length === 0">
              <mat-icon>people_outline</mat-icon>
              <h3>No se encontraron empleados</h3>
              <p *ngIf="searchTerm">Intente ajustar sus criterios de búsqueda.</p>
              <p *ngIf="!searchTerm">Comience agregando su primer empleado.</p>
              <button 
                mat-raised-button 
                color="primary" 
                (click)="createEmployee()"
                *ngIf="employeeService.employees().length === 0">
                <mat-icon>person_add</mat-icon>
                Agregar Primer Empleado
              </button>
            </div>
          </div>
        </mat-card-content>
      </mat-card>
    </div>
  `,
  styles: [`
    .employee-list-container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 20px;
    }

    .header-actions {
      display: flex;
      justify-content: space-between;
      align-items: center;
      width: 100%;
      margin-bottom: 20px;
    }

    .actions {
      display: flex;
      align-items: center;
      gap: 16px;
    }

    .filters-container {
      display: flex;
      align-items: center;
      gap: 12px;
      flex-wrap: wrap;
    }

    .search-field {
      width: 300px;
    }

    .salary-field {
      width: 160px;
    }

    .clear-filters-btn {
      margin-top: 8px;
    }

    .loading-container, 
    .error-container {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      padding: 40px;
      text-align: center;
    }

    .error-container mat-icon {
      font-size: 48px;
      width: 48px;
      height: 48px;
      margin-bottom: 16px;
    }

    .table-container {
      overflow-x: auto;
      margin-top: 20px;
    }

    .employees-table {
      width: 100%;
      margin-top: 20px;
    }

    .action-buttons {
      display: flex;
      gap: 8px;
    }

    .no-data {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      padding: 60px 20px;
      text-align: center;
      color: #666;
    }

    .no-data mat-icon {
      font-size: 64px;
      width: 64px;
      height: 64px;
      margin-bottom: 16px;
      opacity: 0.5;
    }

    .no-data h3 {
      margin: 16px 0 8px 0;
      color: #333;
    }

    .no-data p {
      margin: 8px 0;
      opacity: 0.7;
    }

    mat-card {
      margin-bottom: 20px;
    }

    @media (max-width: 768px) {
      .header-actions {
        flex-direction: column;
        align-items: stretch;
        gap: 16px;
      }

      .actions {
        flex-direction: column;
        align-items: stretch;
      }

      .filters-container {
        flex-direction: column;
        align-items: stretch;
      }

      .search-field,
      .salary-field {
        width: 100%;
      }
    }
  `]
})
export class EmployeeListComponent implements OnInit {
  protected readonly employeeService = inject(EmployeeService);
  private readonly router = inject(Router);
  private readonly snackBar = inject(MatSnackBar);
  private readonly dialog = inject(MatDialog);

  searchTerm = '';
  minSalary: number | null = null;
  maxSalary: number | null = null;
  displayedColumns: string[] = ['fullName', 'email', 'position', 'salary', 'hireDate', 'actions'];

  filteredEmployees = computed(() => {
    const employees = this.employeeService.employees();
    
    return employees.filter(employee => {
      // Filtro por término de búsqueda
      const matchesSearch = !this.searchTerm || 
        employee.fullName.toLowerCase().includes(this.searchTerm.toLowerCase()) ||
        employee.email.toLowerCase().includes(this.searchTerm.toLowerCase()) ||
        employee.position.toLowerCase().includes(this.searchTerm.toLowerCase());
      
      // Filtro por rango salarial
      const matchesSalary = 
        (!this.minSalary || employee.salary >= this.minSalary) &&
        (!this.maxSalary || employee.salary <= this.maxSalary);
      
      return matchesSearch && matchesSalary;
    });
  });

  ngOnInit(): void {
    this.loadEmployees();
  }

  loadEmployees(): void {
    this.employeeService.getEmployees().subscribe();
  }

  refreshEmployees(): void {
    this.employeeService.clearError();
    this.loadEmployees();
  }

  onSearchChange(): void {
    // The computed signal will automatically update the filtered results
  }

  onSalaryFilterChange(): void {
    // The computed signal will automatically update the filtered results
  }

  clearFilters(): void {
    this.searchTerm = '';
    this.minSalary = null;
    this.maxSalary = null;
  }

  createEmployee(): void {
    this.router.navigate(['/employees/create']);
  }

  viewEmployee(id: number): void {
    this.router.navigate(['/employees', id]);
  }

  editEmployee(id: number): void {
    this.router.navigate(['/employees', id, 'edit']);
  }

  confirmDelete(employee: Employee): void {
    if (confirm(`¿Está seguro de que desea eliminar a ${employee.fullName}?`)) {
      this.deleteEmployee(employee.id);
    }
  }

  private deleteEmployee(id: number): void {
    this.employeeService.deleteEmployee(id).subscribe({
      next: () => {
        this.snackBar.open('Empleado eliminado exitosamente', 'Cerrar', {
          duration: 3000,
          panelClass: ['success-snackbar']
        });
      },
      error: () => {
        this.snackBar.open('Error al eliminar empleado', 'Cerrar', {
          duration: 3000,
          panelClass: ['error-snackbar']
        });
      }
    });
  }
}

// frontend/react-app/src/components/EmployeeList.tsx
import React, { useState, useMemo } from 'react';
import { Link } from 'react-router-dom';
import { useEmployees, useDeleteEmployee } from '../hooks/useEmployee';
import { Employee } from '../types/employee';

const EmployeeList: React.FC = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [minSalary, setMinSalary] = useState<string>('');
  const [maxSalary, setMaxSalary] = useState<string>('');
  const { data: employees, isLoading, error, refetch } = useEmployees();
  const deleteEmployee = useDeleteEmployee();

  const filteredEmployees = useMemo(() => {
    if (!employees) return [];
    
    return employees.filter(employee => {
      // Filtro por término de búsqueda
      const matchesSearch = !searchTerm || [
        employee.fullName,
        employee.email,
        employee.position
      ].some(field => field.toLowerCase().includes(searchTerm.toLowerCase()));
      
      // Filtro por salario mínimo
      const minSalaryNum = parseFloat(minSalary);
      const matchesMinSalary = !minSalary || isNaN(minSalaryNum) || employee.salary >= minSalaryNum;
      
      // Filtro por salario máximo
      const maxSalaryNum = parseFloat(maxSalary);
      const matchesMaxSalary = !maxSalary || isNaN(maxSalaryNum) || employee.salary <= maxSalaryNum;
      
      return matchesSearch && matchesMinSalary && matchesMaxSalary;
    });
  }, [employees, searchTerm, minSalary, maxSalary]);

  const handleDelete = async (employee: Employee) => {
    if (window.confirm(`¿Está seguro de que desea eliminar a ${employee.fullName}?`)) {
      try {
        await deleteEmployee.mutateAsync(employee.id);
        // Success message will be handled by the mutation
      } catch (error) {
        console.error('Failed to delete employee:', error);
        alert('Error al eliminar empleado. Por favor, inténtelo de nuevo.');
      }
    }
  };

  const formatSalary = (salary: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(salary);
  };

  const clearFilters = () => {
    setSearchTerm('');
    setMinSalary('');
    setMaxSalary('');
  };

  const hasActiveFilters = searchTerm || minSalary || maxSalary;

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-96">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
        <span className="ml-3 text-lg">Cargando empleados...</span>
      </div>
    );
  }

  if (error) {
    return (
      <div className="bg-red-50 border border-red-200 rounded-lg p-6 text-center">
        <div className="text-red-600 text-6xl mb-4">⚠️</div>
        <h3 className="text-lg font-semibold text-red-800 mb-2">Error al cargar empleados</h3>
        <p className="text-red-600 mb-4">
          {error instanceof Error ? error.message : 'Ocurrió un error inesperado'}
        </p>
        <button
          onClick={() => refetch()}
          className="bg-red-600 hover:bg-red-700 text-white font-bold py-2 px-4 rounded transition-colors"
        >
          Intentar de nuevo
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header & Search */}
      <div className="bg-white shadow-sm rounded-lg p-6">
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Gestión de Empleados</h1>
            <p className="text-gray-600 mt-1">
              {filteredEmployees.length} de {employees?.length || 0} empleado{employees?.length !== 1 ? 's' : ''}
              {hasActiveFilters && ' (filtrados)'}
            </p>
          </div>
          <div className="flex flex-col sm:flex-row gap-4">
            <Link
              to="/employees/create"
              className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-lg transition-colors flex items-center justify-center order-last sm:order-none"
            >
              <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
              </svg>
              Agregar Empleado
            </Link>
          </div>
        </div>
        
        {/* Filtros */}
        <div className="mt-6 pt-6 border-t border-gray-200">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            {/* Búsqueda por texto */}
            <div className="md:col-span-2">
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Buscar empleados
              </label>
              <div className="relative">
                <input
                  type="text"
                  placeholder="Nombre, email o cargo..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500 w-full"
                />
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center">
                  <svg className="w-5 h-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                  </svg>
                </div>
              </div>
            </div>
            
            {/* Salario mínimo */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Salario mínimo
              </label>
              <div className="relative">
                <input
                  type="number"
                  placeholder="Ej: 30000"
                  value={minSalary}
                  onChange={(e) => setMinSalary(e.target.value)}
                  className="pl-8 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500 w-full"
                />
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center">
                  <span className="text-gray-400 text-sm">$</span>
                </div>
              </div>
            </div>
            
            {/* Salario máximo */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Salario máximo
              </label>
              <div className="relative">
                <input
                  type="number"
                  placeholder="Ej: 100000"
                  value={maxSalary}
                  onChange={(e) => setMaxSalary(e.target.value)}
                  className="pl-8 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500 w-full"
                />
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center">
                  <span className="text-gray-400 text-sm">$</span>
                </div>
              </div>
            </div>
          </div>
          
          {/* Botón de limpiar filtros */}
          {hasActiveFilters && (
            <div className="mt-4 text-right">
              <button
                onClick={clearFilters}
                className="text-sm text-gray-600 hover:text-gray-800 underline"
              >
                Limpiar todos los filtros
              </button>
            </div>
          )}
        </div>
      </div>

      {/* Employee Table */}
      {filteredEmployees.length === 0 ? (
        <div className="bg-white shadow-sm rounded-lg p-12 text-center">
          <div className="text-gray-400 text-6xl mb-4">👥</div>
          <h3 className="text-lg font-semibold text-gray-900 mb-2">
            {searchTerm ? 'No se encontraron empleados' : 'Aún no hay empleados'}
          </h3>
          <p className="text-gray-600 mb-6">
            {searchTerm 
              ? 'Intente ajustar sus criterios de búsqueda.' 
              : 'Comience agregando su primer empleado.'
            }
          </p>
          {!searchTerm && (
            <Link
              to="/employees/create"
              className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-lg transition-colors inline-flex items-center"
            >
              <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
              </svg>
              Agregar Primer Empleado
            </Link>
          )}
        </div>
      ) : (
        <div className="bg-white shadow-sm rounded-lg overflow-hidden">
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Empleado
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Cargo
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Salario
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Fecha de Contratación
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Acciones
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {filteredEmployees.map((employee) => (
                  <tr key={employee.id} className="hover:bg-gray-50">
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center">
                        <div className="flex-shrink-0 h-10 w-10">
                          <div className="h-10 w-10 rounded-full bg-blue-500 flex items-center justify-center text-white font-semibold">
                            {employee.firstName.charAt(0)}{employee.lastName.charAt(0)}
                          </div>
                        </div>
                        <div className="ml-4">
                          <div className="text-sm font-medium text-gray-900">
                            {employee.fullName}
                          </div>
                          <div className="text-sm text-gray-500">
                            <a href={`mailto:${employee.email}`} className="hover:text-blue-600">
                              {employee.email}
                            </a>
                          </div>
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      {employee.position}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900 font-semibold">
                      {formatSalary(employee.salary)}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {formatDate(employee.hireDate)}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                      <div className="flex space-x-2">
                        <Link
                          to={`/employees/${employee.id}`}
                          className="text-blue-600 hover:text-blue-900 font-medium"
                        >
                          Ver
                        </Link>
                        <Link
                          to={`/employees/${employee.id}/edit`}
                          className="text-indigo-600 hover:text-indigo-900 font-medium"
                        >
                          Editar
                        </Link>
                        <button
                          onClick={() => handleDelete(employee)}
                          disabled={deleteEmployee.isPending}
                          className="text-red-600 hover:text-red-900 font-medium disabled:opacity-50"
                        >
                          {deleteEmployee.isPending ? 'Eliminando...' : 'Eliminar'}
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
};

export default EmployeeList;
